Adding examples for ARF/mDL, fixes #144
oauth-wg/oauth-sd-jwt-vc pull request #170
Opened 2023-09-29 08:42 UTC by danielfett

2023-09-29 09:16 UTC, paulbastian requested changes

2023-09-29 09:16 UTC, paulbastian commented on examples/05-arf-pid/specification.yml
> +  !sd first_name: Erika
```suggestion
  !sd given_name: Erika
```

2023-09-29 09:16 UTC, paulbastian commented on examples/04-iso18013-5/specification.yml
> +    validUntil: "2027-01-02T00:00:00Z"
Why are these not using iat, exp?

2023-09-29 09:16 UTC, paulbastian commented on examples/03-eaa-diploma/specification.yml
> +  credentialSubject:
Whats the use of credentialSubject here?

2023-09-29 09:16 UTC, paulbastian commented on examples/03-eaa-diploma/specification.yml
> +  binding:
I expect this to be the equievalent of cnf for claim-based binding. This should be a standardized claim in the spec imo.

2023-09-29 09:16 UTC, paulbastian commented on examples/03-eaa-diploma/specification.yml
> +      type: ClaimsBinding2022
```suggestion
      birth_date: '1973-01-01'
      family_name: Mustermann
      given_name: Erika
```

2023-10-14 10:41 UTC, peacekeeper commented
Thank you for your efforts on this. Please allow some time for participants from the EBSI community to review this.

2023-10-14 20:53 UTC, paulbastian commented
Fyi: To my knowledge, the examples will be split into separate PRs and will undergo some changes

2023-10-16 11:45 UTC, peacekeeper commented
In all the SD-JWT VC work, why does it sometimes use "credentialSubject" from the VCDM, and sometimes not?

2023-10-16 11:57 UTC, paulbastian commented
In my opinion, examples with credentialSubject are deprecated

2023-10-16 12:01 UTC, awoie commented
> Fyi: To my knowledge, the examples will be split into separate PRs and will undergo some changes

Yes, those examples will undergo some changes.

2023-10-16 12:08 UTC, peacekeeper commented
So this means that by now, compatibility of SD-JWT VC with VCDM has been completely abandoned, right? At this point, we're faced not only with different proof formats, but also completely different data models.

2024-02-27 18:06 UTC, danielfett commented
As discussed, separate PRs will be created for the examples.

2024-02-27 18:06 UTC, closed without merging