Update CODEOWNERS
oauth-wg/oauth-sd-jwt-vc pull request #188
Opened 2023-11-10 19:32 UTC by bc-pi

2023-11-10 20:34 UTC, bc-pi commented on .github/CODEOWNERS
> +draft-ietf-oauth-sd-jwt-vc.md oliver.terbu@spruceid.com mail@danielfett.de bcampbell@pingidentity.com
github says "this CODEOWNERS file contains errors" and "Unknown owner on line 3: make sure a user with the email address mail@danielfett.de exists and has write access to the repository"
  
```suggestion
draft-ietf-oauth-sd-jwt-vc.md oliver.terbu@spruceid.com fett@danielfett.de bcampbell@pingidentity.com
```

2023-11-21 03:17 UTC, awoie requested changes

2023-11-21 03:17 UTC, awoie commented on .github/CODEOWNERS
> +draft-ietf-oauth-sd-jwt-vc.md oliver.terbu@spruceid.com fett@danielfett.de bcampbell@pingidentity.com
```suggestion
draft-ietf-oauth-sd-jwt-vc.md oliver.terbu@mattr.global fett@danielfett.de bcampbell@pingidentity.com
```

2023-11-21 03:17 UTC, awoie approved these changes
lgtm

2023-11-21 07:53 UTC, merged