Clarify the optionality of the cnf claim
oauth-wg/oauth-sd-jwt-vc pull request #213
Opened 2024-02-20 21:49 UTC by bc-pi

Clarify the optionality of the cnf claim (to fix #196)

2024-02-20 21:51 UTC, Sakurann approved these changes

2024-02-20 21:55 UTC, Sakurann requested changes
Even if there might be a difference in how a key inside cnf claim is represented (jwk, kid, etc) it should still be cnf claim for the interop purposes, no? What are you trying to account for by making cnf optional?

I think it should remain "required when cryptographic binding is used"

2024-02-20 21:56 UTC, bc-pi commented
> Hang on. Even if there might be a difference in how a key inside cnf claim is represented (jwk, kid, etc) it should still be cnf claim for the interop purposes, no? What are you trying to account for by making cnf optional?

please see https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/213

2024-02-21 06:39 UTC, Sakurann commented
@bc-pi you probably made the comment while I was updating my original comment based on re-reading the PR. I still think it should remain "required when cryptographic binding is used"

2024-02-21 07:26 UTC, paulbastian approved these changes
I like this version. CNF is more optional to me and having required as the first keyword seems less right

2024-02-21 17:42 UTC, paulbastian commented
No, I just mean SD-JWT VCs can be key bound, but they don't need to be. Therefore it is an optional feature.

2024-02-21 17:45 UTC, paulbastian commented
I see, the difference here is that if key binding shall be used, then cnf must be used while the other formulation leaves more space?

2024-02-21 17:51 UTC, Sakurann commented
If that's the intent, `required when cryptographic binding is used` sounds more appropriate to me. just saying `optional` would lead to confusion that it is optional even when cryptographic binding is used.

2024-02-21 19:33 UTC, awoie commented
I also like the proposed version more. The proposed language addresses #196 which is based on developer feedback that were confused by the current language that uses REQUIRED if ... . 

So I think that OPTIONAL seems to solve that issue. IMO, it is also appropriate since we have the additional requirement in the paragraph that says MUST be present if cryptographic binding is required.

2024-02-21 19:34 UTC, awoie approved these changes
lgtm, see my comment in the discussion.

2024-02-23 16:52 UTC, paulbastian commented
> > if key binding shall be used, then cnf must be used while the other formulation leaves more space?
> 
> Sorry, I don't understand why more space is needed here? The less optionality in key binding, more interop. with the current PR, it would be ok to use a top level sub claim and put a DID there (instead of using cnf.kid). I think it is harmful for the interop, that SD-JWT VC is hoped to bring

I see your point. The proposed text opens a door for key binding without using the cnf claim. However, the new text is more initiative and we could add this constraint as an additional sentence or in the section on key binding

2024-02-23 17:27 UTC, bc-pi commented
> > > if key binding shall be used, then cnf must be used while the other formulation leaves more space?
> > 
> > 
> > Sorry, I don't understand why more space is needed here? The less optionality in key binding, more interop. with the current PR, it would be ok to use a top level sub claim and put a DID there (instead of using cnf.kid). I think it is harmful for the interop, that SD-JWT VC is hoped to bring
> 
> I don't see that this optionality is allowed by the following?
> 
> > This claim MUST be present when cryptographic Key Binding is to be supported.

2024-02-23 18:10 UTC, paulbastian commented
Okay, it is already present. Sorry I didn't recheck the changes. Lgtm then

2024-02-23 18:52 UTC, bc-pi commented
I'm struggling to understand the disagreement/argument here. But I'm trying...

The text for cnf in the PR has:

>  OPTIONAL. Contains the confirmation method identifying the proof of possession key as defined in [@!RFC7800]. This claim MUST be present when cryptographic Key Binding is to be supported. It is RECOMMENDED that this contains a JWK as defined in Section 3.2 of [@!RFC7800]. For proof of cryptographic Key Binding, the Key Binding JWT in the presentation of the SD-JWT MUST be signed by the key identified in this claim.

which seems to me to clearly says that cnf is the required way to do key binding, if doing key binding. Especially the "This claim MUST be present when cryptographic Key Binding is to be supported" sentence. 

Would changing that sentence to "This claim is REQUIRED when cryptographic Key Binding is to be supported" help? Maybe I'm missing the point of contention but that and the current PR text and the current text in the draft all say the same thing - that cnf is the one and only way to do key binding in SD-JWT VC but b/c key binding isn't itself required, the claim also isn't required.

2024-02-26 17:52 UTC, bc-pi commented on draft-ietf-oauth-sd-jwt-vc.md
> +    * OPTIONAL. Contains the confirmation method identifying the proof of possession key as defined in [@!RFC7800]. This claim MUST be present when cryptographic Key Binding is to be supported. It is
changing that one sentence to "This claim is REQUIRED when cryptographic Key Binding is to be supported"

```suggestion
    * OPTIONAL. Contains the confirmation method identifying the proof of possession key as defined in [@!RFC7800]. This claim is REQUIRED when cryptographic Key Binding is to be supported. It is RECOMMENDED that this contains a JWK as defined in Section 3.2 of [@!RFC7800]. For proof of cryptographic Key Binding, the Key Binding JWT in the presentation of the SD-JWT MUST be signed by the key identified in this claim.
```

2024-02-27 16:12 UTC, danielfett commented on draft-ietf-oauth-sd-jwt-vc.md
> +    * OPTIONAL. Contains the confirmation method identifying the proof of possession key as defined in [@!RFC7800]. This claim is REQUIRED when cryptographic Key Binding is to be supported. It is REC
_Technically,_ the REQUIRED contradicts the OPTIONAL. So in order to not trigger any RFC2119 nerds, we could use: 
```suggestion
    * OPTIONAL unless cryptographic Key Binding is to be supported, in which case it is REQUIRED. Contains the confirmation method identifying the proof of possession key as defined in [@!RFC7800]. It is RECOMMENDED that this contains a JWK as defined in Section 3.2 of [@!RFC7800]. For proof of cryptographic Key Binding, the Key Binding JWT in the presentation of the SD-JWT MUST be signed by the key identified in this claim.
```

2024-02-27 16:14 UTC, danielfett approved these changes
I'm generally fine with the change, but I think I want to be pedantic here and resolve the contradiction.

2024-02-27 16:27 UTC, bc-pi commented
> I'm generally fine with the change, but I think I want to be pedantic here and resolve the contradiction.

You're suggested pedantic wording is indeed better than what I'd had. Thanks. I've accepted it w/ c6b138036e035e6df2a2f983aa4cf8b183d39fc2

2024-02-27 18:22 UTC, Sakurann approved these changes
thank you!

2024-02-27 19:05 UTC, merged