Fix #234 (Improve Example)
oauth-wg/oauth-sd-jwt-vc pull request #235
Opened 2024-06-05 08:36 UTC by danielfett

Fixes #234

2024-06-05 16:59 UTC, bc-pi approved these changes

2024-06-10 21:49 UTC, bc-pi commented on draft-ietf-oauth-sd-jwt-vc.md
> +  "vct#integrity": "sha256-oTxxE//FNomPebw6yH9aNuEPUjbiYqaxBj1ZgMMBsxHmjTOBDhRiVCUD2bhVlzYg",
wait... `oTxxE//FNomPebw6yH9aNuEPUjbiYqaxBj1ZgMMBsxHmjTOBDhRiVCUD2bhVlzYg` decodes to 48 bytes, which doesn't track too well with `sha256` while `WRL5ca_xGgX3c1VLmXfh-9cLlJNXN-TsMk-PmKjZ5t0` is the 32 bytes one would expect. Why'd you change this value?

2024-06-10 21:49 UTC, bc-pi commented on draft-ietf-oauth-sd-jwt-vc.md
> +`oTxxE//FNomPebw6yH9aNuEPUjbiYqaxBj1ZgMMBsxHmjTOBDhRiVCUD2bhVlzYg`.
see also https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/235/files#r1633871626

2024-06-10 21:50 UTC, bc-pi requested changes
how many bytes would a vct#integrity byte if a vct#integrity could byte integrity?

2024-07-01 15:43 UTC, awoie requested changes
looks good to me but @bc-pi comment has to be fixed

2024-07-01 17:00 UTC, bc-pi commented on draft-ietf-oauth-sd-jwt-vc.md
> +  "vct#integrity": "sha256-oTxxE//FNomPebw6yH9aNuEPUjbiYqaxBj1ZgMMBsxHmjTOBDhRiVCUD2bhVlzYg",
```suggestion
  "vct#integrity": "sha256-WRL5ca_xGgX3c1VLmXfh-9cLlJNXN-TsMk-PmKjZ5t0",
```

2024-07-01 17:01 UTC, bc-pi commented on draft-ietf-oauth-sd-jwt-vc.md
> +`oTxxE//FNomPebw6yH9aNuEPUjbiYqaxBj1ZgMMBsxHmjTOBDhRiVCUD2bhVlzYg`.
```suggestion
`WRL5ca_xGgX3c1VLmXfh-9cLlJNXN-TsMk-PmKjZ5t0`.
```

2024-07-01 17:05 UTC, bc-pi approved these changes

2024-07-01 18:55 UTC, awoie approved these changes

2024-07-01 19:32 UTC, merged